// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzM_FPSN6KS9BcDcQvZCrRx1zN2fSD0Ro',
    appId: '1:1013453062413:web:e17e17e6370a3e09c27044',
    messagingSenderId: '1013453062413',
    projectId: 'projetiot-81b27',
    authDomain: 'projetiot-81b27.firebaseapp.com',
    databaseURL: 'https://projetiot-81b27-default-rtdb.firebaseio.com',
    storageBucket: 'projetiot-81b27.appspot.com',
    measurementId: 'G-STHEJMW14X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQLghriQQKvE1FW0FfWE74RZbzZ_y14Ao',
    appId: '1:1013453062413:android:0ca49d5a485f1826c27044',
    messagingSenderId: '1013453062413',
    projectId: 'projetiot-81b27',
    databaseURL: 'https://projetiot-81b27-default-rtdb.firebaseio.com',
    storageBucket: 'projetiot-81b27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFj5U1n0oUOMApX1oG5y_BuGSduq5N8cE',
    appId: '1:1013453062413:ios:028eeb2b9e019b2dc27044',
    messagingSenderId: '1013453062413',
    projectId: 'projetiot-81b27',
    databaseURL: 'https://projetiot-81b27-default-rtdb.firebaseio.com',
    storageBucket: 'projetiot-81b27.appspot.com',
    iosClientId: '1013453062413-h3csl5rn9s6ikbf8dpv8p6b5bdo7ph15.apps.googleusercontent.com',
    iosBundleId: 'com.example.uuuuuuuuuuu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFj5U1n0oUOMApX1oG5y_BuGSduq5N8cE',
    appId: '1:1013453062413:ios:028eeb2b9e019b2dc27044',
    messagingSenderId: '1013453062413',
    projectId: 'projetiot-81b27',
    databaseURL: 'https://projetiot-81b27-default-rtdb.firebaseio.com',
    storageBucket: 'projetiot-81b27.appspot.com',
    iosClientId: '1013453062413-h3csl5rn9s6ikbf8dpv8p6b5bdo7ph15.apps.googleusercontent.com',
    iosBundleId: 'com.example.uuuuuuuuuuu',
  );
}
